### ISSUE TITLE
String incorreta no arquivo NotaFiscal

### ISSUE THREAD

**Issue by renatodex** [organisys/bling-ruby#3]
Olá,
Tudo bom?

Há um erro na linha 102 do arquivo nota_fiscal:
  
https://github.com/organisys/bling-ruby/blob/e483948b6aa283ca0517f099e84809b670cc6e0a/lib/bling/nota_fiscal.rb#L102
  
O correto deveria ser "notasfiscais" e não "notasservico".
Estou sem tempo pra fazer esse Pull Request, mas se quiserem podem arrumar.

][`s

**Comment by lucianosousa** [comment]
@renatodex https://github.com/organisys/bling-ruby/pull/4

pode validar?
